// Mocks generated by Mockito 5.4.4 from annotations
// in dinner_sticks/test/domain/usecases/delete_stick_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dinner_sticks/domain/entities/pool.dart' as _i2;
import 'package:dinner_sticks/domain/entities/stick.dart' as _i3;
import 'package:dinner_sticks/domain/entities/weekly_bin.dart' as _i4;
import 'package:dinner_sticks/domain/repositories/pool_repository.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePool_0 extends _i1.SmartFake implements _i2.Pool {
  _FakePool_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStick_1 extends _i1.SmartFake implements _i3.Stick {
  _FakeStick_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWeeklyBin_2 extends _i1.SmartFake implements _i4.WeeklyBin {
  _FakeWeeklyBin_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PoolRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPoolRepository extends _i1.Mock implements _i5.PoolRepository {
  MockPoolRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Stream<List<_i2.Pool>> watchAllPools() => (super.noSuchMethod(
        Invocation.method(
          #watchAllPools,
          [],
        ),
        returnValue: _i6.Stream<List<_i2.Pool>>.empty(),
      ) as _i6.Stream<List<_i2.Pool>>);

  @override
  _i6.Future<_i2.Pool> createPool(String? name) => (super.noSuchMethod(
        Invocation.method(
          #createPool,
          [name],
        ),
        returnValue: _i6.Future<_i2.Pool>.value(_FakePool_0(
          this,
          Invocation.method(
            #createPool,
            [name],
          ),
        )),
      ) as _i6.Future<_i2.Pool>);

  @override
  _i6.Future<_i2.Pool> renamePool(
    String? poolId,
    String? newName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #renamePool,
          [
            poolId,
            newName,
          ],
        ),
        returnValue: _i6.Future<_i2.Pool>.value(_FakePool_0(
          this,
          Invocation.method(
            #renamePool,
            [
              poolId,
              newName,
            ],
          ),
        )),
      ) as _i6.Future<_i2.Pool>);

  @override
  _i6.Future<void> deletePool(String? poolId) => (super.noSuchMethod(
        Invocation.method(
          #deletePool,
          [poolId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Stream<List<_i3.Stick>> watchSticks(String? poolId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchSticks,
          [poolId],
        ),
        returnValue: _i6.Stream<List<_i3.Stick>>.empty(),
      ) as _i6.Stream<List<_i3.Stick>>);

  @override
  _i6.Future<_i3.Stick> addStick(
    String? poolId,
    String? name,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addStick,
          [
            poolId,
            name,
          ],
        ),
        returnValue: _i6.Future<_i3.Stick>.value(_FakeStick_1(
          this,
          Invocation.method(
            #addStick,
            [
              poolId,
              name,
            ],
          ),
        )),
      ) as _i6.Future<_i3.Stick>);

  @override
  _i6.Future<_i3.Stick> editStick(
    String? stickId,
    String? newName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #editStick,
          [
            stickId,
            newName,
          ],
        ),
        returnValue: _i6.Future<_i3.Stick>.value(_FakeStick_1(
          this,
          Invocation.method(
            #editStick,
            [
              stickId,
              newName,
            ],
          ),
        )),
      ) as _i6.Future<_i3.Stick>);

  @override
  _i6.Future<void> deleteStick(String? stickId) => (super.noSuchMethod(
        Invocation.method(
          #deleteStick,
          [stickId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i4.WeeklyBin?> getWeeklyBin(String? poolId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWeeklyBin,
          [poolId],
        ),
        returnValue: _i6.Future<_i4.WeeklyBin?>.value(),
      ) as _i6.Future<_i4.WeeklyBin?>);

  @override
  _i6.Stream<_i4.WeeklyBin?> watchWeeklyBin(String? poolId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchWeeklyBin,
          [poolId],
        ),
        returnValue: _i6.Stream<_i4.WeeklyBin?>.empty(),
      ) as _i6.Stream<_i4.WeeklyBin?>);

  @override
  _i6.Future<_i4.WeeklyBin> confirmSelection(
    String? poolId,
    List<String>? stickIds,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #confirmSelection,
          [
            poolId,
            stickIds,
          ],
        ),
        returnValue: _i6.Future<_i4.WeeklyBin>.value(_FakeWeeklyBin_2(
          this,
          Invocation.method(
            #confirmSelection,
            [
              poolId,
              stickIds,
            ],
          ),
        )),
      ) as _i6.Future<_i4.WeeklyBin>);

  @override
  _i6.Future<_i4.WeeklyBin> replaceBinStick(
    String? poolId,
    String? oldStickId,
    String? newStickId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceBinStick,
          [
            poolId,
            oldStickId,
            newStickId,
          ],
        ),
        returnValue: _i6.Future<_i4.WeeklyBin>.value(_FakeWeeklyBin_2(
          this,
          Invocation.method(
            #replaceBinStick,
            [
              poolId,
              oldStickId,
              newStickId,
            ],
          ),
        )),
      ) as _i6.Future<_i4.WeeklyBin>);

  @override
  _i6.Future<_i4.WeeklyBin> removeBinStick(
    String? poolId,
    String? stickId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeBinStick,
          [
            poolId,
            stickId,
          ],
        ),
        returnValue: _i6.Future<_i4.WeeklyBin>.value(_FakeWeeklyBin_2(
          this,
          Invocation.method(
            #removeBinStick,
            [
              poolId,
              stickId,
            ],
          ),
        )),
      ) as _i6.Future<_i4.WeeklyBin>);

  @override
  _i6.Future<_i4.WeeklyBin> markStickDone(
    String? poolId,
    String? stickId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markStickDone,
          [
            poolId,
            stickId,
          ],
        ),
        returnValue: _i6.Future<_i4.WeeklyBin>.value(_FakeWeeklyBin_2(
          this,
          Invocation.method(
            #markStickDone,
            [
              poolId,
              stickId,
            ],
          ),
        )),
      ) as _i6.Future<_i4.WeeklyBin>);
}
